version: '3.7'
services:

# -----------------------------------------------------------------
# Database

  mysql_pi-01:
    image: mysql:8.0
    restart: unless-stopped
    container_name: "mysql_pi-01"

    ports:
      - "3306:33061"

    volumes:
      # Configuration
      # - ../config/mysql_pi-01/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      # - ../config/mysql_pi-01/config-file.cnf:/etc/mysql/config-file.cnf:ro
      # - ../config/mysql_pi-01/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro

      # Data Storage
      - ./data/mysql_pi-01:/var/lib/mysql

    command:
       - --default-authentication-plugin=mysql_native_password
       - --character-set-server=utf8mb4
       - --collation-server=utf8mb4_general_ci

    environment:
      MYSQL_ROOT_PASSWORD: 'XHdfSQM1RkoOqc2i2kTY'
      MYSQL_DATABASE: 'mysql_pi-01'
      MYSQL_USER: 'mysql_pi-01'
      MYSQL_PASSWORD: 'F6fmy9l1SzRcD1Zqsxhs'


# -----------------------------------------------------------------
# WebServer

  apache_pi-01:
    image: php:7-apache-buster
    restart: unless-stopped
    container_name: apache_pi-01

    ports:
      - "80:8080"

    volumes:
      # Configuration
      - ./config/apache_pi-01/php.ini:/usr/local/etc/php/php.ini:ro

      # data Storage
      - ./data/apache_pi-01:/var/www/html


# -----------------------------------------------------------------
# Database Management IDE

  phpmyadmin_pi-01:
    image: phpmyadmin:latest
    restart: unless-stopped
    container_name: phpmyadmin_pi-01
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_pi-01
      # - PMA_USER=root
      - PMA_PORT=3306
      - UPLOAD_LIMIT=300M
      - PMA_ABSOLUTE_URI=http://localhost:8081
       
    ports:
      - "80:8081"
      
    volumes:
      # Data Storage
      - ./data/phpmyadmin_pi-01:/sessions

# -----------------------------------------------------------------
