version: '3.7'
services:

# -----------------------------------------------------------------
# WebServer
# Access via: http://localhost:8080

  apache_pi1:
    image: acremonezi/wsgi-base:3.9
    restart: unless-stopped
    container_name: apache_pi1
    build:
      context: .
      args:
        - pyversion=3.9
 
    ports:
      - "8080:80"

    volumes:
      # Data Storage
      - ./app:/var/www/html/
      # Define Time
      - /etc/localtime:/etc/localtime:ro


# -----------------------------------------------------------------
# Database
# Access via: (Host: localhost), (Port:33061) and (User/Passwords are bellow).

  mysql_pi1:
    image: mysql:8.0
    restart: unless-stopped
    container_name: "mysql_pi1"

    ports:
      - "33061:3306"

    volumes:
      # Configuration
      - ./config/mysql/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      # Data Storage
      - ./data/mysql:/var/lib/mysql
      # Define Time
      - /etc/localtime:/etc/localtime:ro

    command:
       - --default-authentication-plugin=mysql_native_password
       - --character-set-server=utf8
       - --collation-server=utf8_general_ci

    environment:
      # Database root user passord:
      MYSQL_ROOT_PASSWORD: 'XHdfSQM1RkoOqc2i2kTY'
      # App Schema Access:
      MYSQL_DATABASE: 'mysql_pi1'
      MYSQL_USER: 'mysql_pi1'
      MYSQL_PASSWORD: 'F6fmy9l1SzRcD1Zqsxhs'

# -----------------------------------------------------------------
# Database Management IDE
# Access via: http://localhost:8081

  phpmyadmin_pi1:
    image: phpmyadmin:latest
    restart: unless-stopped
    container_name: phpmyadmin_pi1
    environment:
      - PMA_HOSTS=mysql_pi1
      - PMA_USER=root
      - PMA_PASSWORD=XHdfSQM1RkoOqc2i2kTY
      - PMA_PORT=3306
      - UPLOAD_LIMIT=300M
      - PMA_ABSOLUTE_URI=http://localhost:8081
       
    ports:
      - "8081:80"
      
    volumes:
      # Data Storage
      - ./data/phpmyadmin_pi1:/sessions

# -----------------------------------------------------------------
