# Generated by Django 3.2.9 on 2021-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_alter_certificate_authentication_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='carga_horaria',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
