# Generated by Django 3.2.9 on 2021-11-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cpf',
            field=models.CharField(default=88546325845, max_length=50),
            preserve_default=False,
        ),
    ]
